const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.WaitForPreviousActions
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{TiledBackground: 0},
	{Sprite: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Sprite2: 0},
	{TiledBackground2: 0},
	{Sprite3: 0},
	{RoastText: 0},
	{RoastArray: 0},
	{Bullet: 0},
	{bullet: 0},
	{Keyboard: 0},
	{PlayerHealthBar: 0},
	{EnemyHealthBar: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{PlayerHealth: 0},
	{EnemyHealth: 0},
	{CanShot: 0},
	{Variable1: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	RoastText: class extends self.ITextInstance {},
	RoastArray: class extends self.IArrayInstance {},
	bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PlayerHealthBar: class extends self.IProgressBarInstance {},
	EnemyHealthBar: class extends self.IProgressBarInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}